
# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# Note that the trigger is ignored and overriden by Azure Pipelines options
resources:
  repositories:
  - repository: yaktest # The name used to reference this repository in the checkout step
    type: github
    endpoint: za
    name: zahidferz/yaktest
    ref: $(Build.SourceBranchName)

  - repository: gx-yak-tests # The name used to reference this repository in the checkout step
    type: github
    endpoint: gx-github
    name: gestionix/gx-yak-tests

name: $(SourceBranchName)
pool:
  vmImage: 'Ubuntu-16.04'

jobs:

  - job: GetVersion
    displayName: Get Version
    steps:
      - bash: |
          VERSIONT=$(jq -r .version package.json)
          echo "##vso[task.setvariable variable=version;isOutput=true]$VERSIONT"
        name: App

  - job: Build
    displayName: Build
    dependsOn: GetVersion
    variables:
      appVersion: $[ dependencies.GetVersion.outputs['App.version'] ]
      buildIncrement: $[counter(variables['appVersion'], 0)] # create a counter that is used to increment build run for same app version
      buildVersion: '$(appVersion)-r$(buildIncrement)'
    steps:
      - bash: echo "##vso[build.updatebuildnumber]$(buildVersion)" # Update build number in Pipeline UI
        displayName: Update build number

      - bash: echo $(IP) && echo "##vso[task.setvariable variable=IP;]192.168.100.1"

      - bash: echo $(IP)
      
  - job: Test
    displayName: Test
    dependsOn: GetVersion
    steps:

      - bash: sleep 10 & echo $(IP) 
